[project]
name = "gtmforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "decorator>=5.2.1",
    "fastapi>=0.118.2",
    "google-adk[a2a]>=1.17.0",
    "google-generativeai>=0.8.3",
    "imageio>=2.37.0",
    "imageio-ffmpeg>=0.6.0",
    "markdown>=3.6",
    "moviepy>=2.2.1",
    "pillow>=11.3.0",
    "proglog>=0.1.12",
    "tqdm>=4.67.1",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pytest>=8.4.2",
]
