# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pydantic data models for GTMForge."""

from typing import Optional, Union

from pydantic import BaseModel, Field


class AssetBase(BaseModel):
    """Base model for assets to be saved by the asset service.

    This model defines the common structure for assets. All assets must have
    a content field, mime_type, and optionally a filename for saving to disk.
    """

    content: str = Field(
        description="The actual content of the asset (text, HTML, markdown, etc.)"
    )
    mime_type: str = Field(
        default="text/plain",
        description="MIME type of the asset (e.g., 'text/markdown', 'image/png')",
    )
    filename: Optional[str] = Field(
        default=None,
        description="Filename for the asset. If not provided, will be auto-generated from name/id fields or index.",
    )


class ReportAsset(AssetBase):
    """Model for research report assets.

    Used to save research reports generated by agents to the asset server.
    Default MIME type: text/markdown
    """

    mime_type: str = Field(
        default="text/markdown",
        description="MIME type of the report (default: text/markdown)",
    )
    name: str = Field(
        default="research_report",
        description="Name of the report file (without extension)",
    )
    title: Optional[str] = Field(
        default=None, description="Optional human-readable title for the report"
    )


class ImageAsset(AssetBase):
    """Model for image assets.

    Used for storing generated or processed images.
    Note: content should be base64-encoded image data.
    Default MIME type: image/png
    """

    mime_type: str = Field(
        default="image/png",
        description="MIME type of the image (default: image/png)",
    )
    name: str = Field(default="image", description="Name of the image file")
    alt_text: Optional[str] = Field(
        default=None, description="Alternative text for accessibility"
    )


class DocumentAsset(AssetBase):
    """Model for generic document assets.

    Used for any text-based documents (markdown, HTML, plain text, etc.).
    Default MIME type: text/markdown
    """

    mime_type: str = Field(
        default="text/markdown",
        description="MIME type of the document (default: text/markdown)",
    )
    name: str = Field(default="document", description="Name of the document file")
    format: str = Field(
        default="markdown",
        description="Document format (markdown, html, txt, etc.)",
    )


class VideoAsset(BaseModel):
    """Model for video assets.

    Used for storing generated or processed videos.
    Note: content should be the video data or a reference to it.
    Default MIME type: video/mp4
    """

    content: bytes = Field(description="The video data")
    mime_type: str = Field(
        default="video/mp4", description="MIME type of the video (default: video/mp4)"
    )
    name: str = Field(default="video", description="Name of the video file")
    filename: Optional[str] = Field(
        default=None, description="Filename for the video file"
    )
    duration: Optional[float] = Field(
        default=None, description="Video duration in seconds"
    )


class Assets(BaseModel):
    """Container for a collection of assets to be saved together.

    This model represents a batch of assets that should be saved to the same
    session and asset type folder. Assets can have different MIME types - they
    will be automatically grouped and saved accordingly.
    """

    session_id: str = Field(description="Unique identifier for the session")
    asset_type: str = Field(
        description="Type of assets (e.g., 'reports', 'images', 'videos', 'documents')"
    )
    items: list[Union[AssetBase, ReportAsset, ImageAsset, DocumentAsset, VideoAsset]] = Field(
        description="List of asset objects to be saved. Each asset carries its own MIME type."
    )

    def save(self) -> list[dict[str, str]]:
        """Save all assets in this collection.

        Assets with different MIME types are automatically grouped and saved
        separately to ensure proper handling.

        Returns:
            List of dictionaries containing information about saved files.

        Example:
            >>> from forge.data_models import Assets, ReportAsset, ImageAsset
            >>> assets = Assets(
            ...     session_id="abc123",
            ...     asset_type="mixed",
            ...     items=[
            ...         ReportAsset(content="# Report", filename="report.md"),
            ...         ImageAsset(content="base64data", filename="chart.png", mime_type="image/png")
            ...     ]
            ... )
            >>> saved = assets.save()
            >>> print(saved[0]["url"])
            /assets/abc123/mixed/report.md
        """
        from collections import defaultdict
        from forge.utils.asset_services import save_assets

        # Group assets by mime_type
        grouped_assets = defaultdict(list)
        for item in self.items:
            grouped_assets[item.mime_type].append(item)

        # Save each group separately and collect all results
        all_saved_files = []
        for mime_type, assets_group in grouped_assets.items():
            saved_files = save_assets(
                session_id=self.session_id,
                asset_type=self.asset_type,
                assets=assets_group,
                mime_type=mime_type,
            )
            all_saved_files.extend(saved_files)

        return all_saved_files
